### PR TITLE
Fix generate-all-docs

### LINKED ISSUE #95: tanzu generate-all-docs does not generate all core commands
**Bug description**
tanzu generate-all-docs stops short at generating top level commands for the tanzu cli

**Expected behavior**
it should generate documentation recursively for all core commands not originating from a plugin

**Steps to reproduce the bug / Relevant debug output**
```
mkdir -p docs/cli/commands
tanzu generate-all-docs
find docs/cli/commands
```

**Output of `tanzu version`**

version: v0.0.2-dev
buildDate: 2023-03-07
sha: 2bc1c2b2-dirty

**Environment where the bug was observed (cloud, OS, etc)**

### PR DESCRIPTION
**Pull request by vuil**
### What this PR does / why we need it

The core cli commands doc generation did not recurse down the root command tree. This change fixes that.
Did some cleanup and added missing unit test.

### Which issue(s) this PR fixes
Fixes #95

### Describe testing done for PR

```
go test ./pkg/command/... -run TestGenDocs
ok      github.com/vmware-tanzu/tanzu-cli/pkg/command   2.324s

> make build-all
> mkdir docs/cli/commands
# generate docs in docs/cli/commands for core commands and plugins installed
> ./bin/tanzu generate-all-docs
> find docs/cli/commands/ | sort
docs/cli/commands/
docs/cli/commands//README.md
docs/cli/commands//tanzu.md
docs/cli/commands//tanzu_builder.md
docs/cli/commands//tanzu_builder_cli.md
docs/cli/commands//tanzu_builder_cli_add-plugin.md
docs/cli/commands//tanzu_builder_cli_compile.md
docs/cli/commands//tanzu_builder_init.md
docs/cli/commands//tanzu_builder_inventory.md
docs/cli/commands//tanzu_builder_inventory_init.md
docs/cli/commands//tanzu_builder_inventory_plugin-group.md
docs/cli/commands//tanzu_builder_inventory_plugin-group_activate.md
docs/cli/commands//tanzu_builder_inventory_plugin-group_add.md
docs/cli/commands//tanzu_builder_inventory_plugin-group_deactivate.md
docs/cli/commands//tanzu_builder_inventory_plugin.md
docs/cli/commands//tanzu_builder_inventory_plugin_activate.md
docs/cli/commands//tanzu_builder_inventory_plugin_add.md
docs/cli/commands//tanzu_builder_inventory_plugin_deactivate.md
docs/cli/commands//tanzu_builder_plugin.md
docs/cli/commands//tanzu_builder_plugin_build-package.md
docs/cli/commands//tanzu_builder_plugin_build.md
docs/cli/commands//tanzu_builder_plugin_publish-package.md
docs/cli/commands//tanzu_builder_publish.md
docs/cli/commands//tanzu_completion.md
docs/cli/commands//tanzu_config.md
docs/cli/commands//tanzu_config_get.md
docs/cli/commands//tanzu_config_init.md
docs/cli/commands//tanzu_config_server.md
docs/cli/commands//tanzu_config_server_delete.md
docs/cli/commands//tanzu_config_server_list.md
docs/cli/commands//tanzu_config_set.md
docs/cli/commands//tanzu_config_unset.md
docs/cli/commands//tanzu_context.md
docs/cli/commands//tanzu_context_create.md
docs/cli/commands//tanzu_context_delete.md
docs/cli/commands//tanzu_context_get.md
docs/cli/commands//tanzu_context_list.md
docs/cli/commands//tanzu_context_use.md
docs/cli/commands//tanzu_init.md
docs/cli/commands//tanzu_plugin.md
docs/cli/commands//tanzu_plugin_clean.md
docs/cli/commands//tanzu_plugin_delete.md
docs/cli/commands//tanzu_plugin_describe.md
docs/cli/commands//tanzu_plugin_group.md
docs/cli/commands//tanzu_plugin_group_search.md
docs/cli/commands//tanzu_plugin_install.md
docs/cli/commands//tanzu_plugin_list.md
docs/cli/commands//tanzu_plugin_search.md
docs/cli/commands//tanzu_plugin_source.md
docs/cli/commands//tanzu_plugin_source_add.md
docs/cli/commands//tanzu_plugin_source_delete.md
docs/cli/commands//tanzu_plugin_source_list.md
docs/cli/commands//tanzu_plugin_source_update.md
docs/cli/commands//tanzu_plugin_sync.md
docs/cli/commands//tanzu_plugin_upgrade.md
docs/cli/commands//tanzu_test.md
docs/cli/commands//tanzu_test_fetch.md
docs/cli/commands//tanzu_version.md
```

### Release note

```release-note
'tanzu generate-all-docs' generates core commands recursively
```

#### Special notes for your reviewer
A corresponding runtime change to eliminate autogenerated spf13/cobra footer is being made.
Once that change is committed and picked up here, will update the CI to ensure that docs are flagged for diffs in pre-checkins.

### CODE REVIEW

**Comment by marckhouzam** [comment]
Thanks @vuil for this.
The generation seems much better although I think it is not handling targets very well, and also getting confused when a plugin with the same name is installed under two targets.
I'll try to dig deeper a little later.

**Comment by marckhouzam** [comment]
Also, I don't understand how things could have worked in TF and stopped working here...  any ideas?

**Comment by marckhouzam** [comment]
> Also, I don't understand how things could have worked in TF and stopped working here... any ideas?

Doesn't seem to work in TF either... Unless it's me.

**Comment by marckhouzam** [comment]
This PR needs rebasing.

**Review by marckhouzam — COMMENTED** [review]
I don't think this command was every updated to properly handle targets.  Here are issues I've seen.

First, install a plugin under the TMC target:

```
$ tz config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY <internal repo>
$ tz plugin install cluster --target tmc
$ tz plugin list
Standalone Plugins
  NAME     DESCRIPTION                       TARGET           VERSION  STATUS
  cluster  A TMC managed Kubernetes cluster  mission-control  v0.0.1   installed

$ mkdir tmp
$ tz generate-all-docs -d tmp
```
Things that don't work in the generated docs:
1. The `cluster` plugin doc does not respect the `mission-control` target.  
    1. So it is generated as `tanzu_cluster*` instead of `tanzu_mission-control_cluster*`
    1. The `tanzu.md` file does show the `tanzu_mission-control.md` link and not the `tanzu_cluster` one, which is good, but the `tanzu_mission-control.md` does not exist and the link is broken

Now install a plugin with the same name under the k8s target:
```
$ rm -rf tmp
$ mkdir tmp
$ tz plugin install cluster --target k8s
$ tz plugin list
Standalone Plugins
  NAME     DESCRIPTION                       TARGET           VERSION  STATUS
  cluster  Kubernetes cluster operations     kubernetes       v0.28.0  installed
  cluster  A TMC managed Kubernetes cluster  mission-control  v0.0.1   installed

$ tz generate-all-docs -d tmp
```

Now the poorly handled target causes alls files between the same-named `cluster` plugins to be mixed together.

**Comment by vuil** [comment]
> I don't think this command was ever updated to properly handle targets. Here are issues I've seen.
> 
> First, install a plugin under the TMC target:
> 
> ```
> $ tz config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY <internal repo>
> $ tz plugin install cluster --target tmc
> $ tz plugin list
> Standalone Plugins
>   NAME     DESCRIPTION                       TARGET           VERSION  STATUS
>   cluster  A TMC managed Kubernetes cluster  mission-control  v0.0.1   installed
> 
> $ mkdir tmp
> $ tz generate-all-docs -d tmp
> ```
> 
> Things that don't work in the generated docs:
> 
> 1. The `cluster` plugin doc does not respect the `mission-control` target.
>    
>    1. So it is generated as `tanzu_cluster*` instead of `tanzu_mission-control_cluster*`
>    2. The `tanzu.md` file does show the `tanzu_mission-control.md` link and not the `tanzu_cluster` one, which is good, but the `tanzu_mission-control.md` does not exist and the link is broken
> 
> Now install a plugin with the same name under the k8s target:
> 
> ```
> $ rm -rf tmp
> $ mkdir tmp
> $ tz plugin install cluster --target k8s
> $ tz plugin list
> Standalone Plugins
>   NAME     DESCRIPTION                       TARGET           VERSION  STATUS
>   cluster  Kubernetes cluster operations     kubernetes       v0.28.0  installed
>   cluster  A TMC managed Kubernetes cluster  mission-control  v0.0.1   installed
> 
> $ tz generate-all-docs -d tmp
> ```
> 
> Now the poorly handled target causes alls files between the same-named `cluster` plugins to be mixed together.

Yes I noticed this as well. I think it still makes sense to merge this while we file an issue to track generating in the target specific manner. @marckhouzam wdyt?

**Comment by marckhouzam** [comment]
> Yes I noticed this as well. I think it still makes sense to merge this while we file an issue to track generating in the target specific manner. @marckhouzam wdyt?

Ok with me.
Just need to rebase.

**Review by marckhouzam — APPROVED** [review]
This is great @vuil.
LGTM once rebased.
We just need to open an issue to fix the fact that targets are not being respected.

**Comment by marckhouzam** [comment]
@vuil I've rebased this PR and pushed it to this repo under branch `fix/gendocs2`.
I've also re-generated the `docs/cli/commands` documentation with the updated `gen-all-docs` command.
If you want to take this new branch and push it on top of this PR it will save you time.

I decided to regenerate the docs without any plugins installed not even the essentials plugins.
If you feel we should do it differently, it will be easy to re-generate.

To generate the docs with no plugins installed , this is what I did:
```
$ tz plugin source delete default
[ok] deleted discovery source default

# A "tanzu plugin clean" would be better but I didn't want to wipe out my plugin binary cache
$ tz plugin uninstall telemetry
Uninstalling plugin 'telemetry' for target 'global'. Are you sure? [y/N]: y
[i] Uninstalling plugin 'telemetry' for target 'global'
[ok] successfully uninstalled plugin 'telemetry'
$
$ tz generate-all-docs
```

**Comment by vuil** [comment]
sync fix/gendocs2 into source branch, deleted md no longer being generated, but temporarily clean up one reference to a removed markdown file to make the markdown link checker happy. 

Will look to reinstate the plugin related docs in a separate location as a followup.

Thanks @marckhouzam for the review and updates.

**Pull request merged**
