### PR TITLE
Allow plugin inventory cache to work on Windows

### LINKED ISSUE #392: Caching of the plugin inventory image does not work on the windows
**Bug description**

On Windows, whenever the plugin inventory DB is needed, the remote image gets downloaded instead of the cache being used.

It turns out that on Windows, trailing `.` are ignored in file names. But we use a file `metadata.digest.` with a trailing `.` when not using an airgapped image which is the most common case actually.

Since the trailing `.` gets ignored on Windows, the CLI never finds the `metadata.digest.` file and always thinks the cache is invalid.

Notice the missing trailing `.` in the directory list below for the file `metadata.digest`
```
ls .\.cache\tanzu\plugin_inventory\default\

Directory: C:\Users\kmarc\.cache\tanzu\plugin_inventory\default

Mode LastWriteTime Length Name
---- ------------- ------ ----
a--- 6/7/2023 1:38 AM 0 digest.4d9862452d14e8cd8adb5e622b4eced5e22e42d566b97e620a8e30242635fd2f
a--- 6/7/2023 2:24 AM 0 metadata.digest
a--- 6/7/2023 2:24 AM 73728 plugin_inventory.db
```
 
**Expected behavior**

Once the image is downloaded in the cache, it should not need to be re-downloaded unless the image is updated on the remote registry.

**Steps to reproduce the bug / Relevant debug output**

```
PS C:\Users\anujc\Downloads\tanzu-cli-windows-amd64\v0.90.0-rc.0> .\tanzu.exe plugin search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  NAME                DESCRIPTION                                                        TARGET      LATEST
  builder             Build Tanzu components                                             global      v0.90.0-beta.0
  isolated-cluster    Prepopulating images/bundle for internet-restricted environments   global      v0.29.0
[...]
  telemetry           configure cluster-wide settings for vmware tanzu telemetry         kubernetes  v0.29.0

PS C:\Users\anujc\Downloads\tanzu-cli-windows-amd64\v0.90.0-rc.0> .\tanzu.exe plugin search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  NAME                DESCRIPTION                                                        TARGET      LATEST
  builder             Build Tanzu components                                             global      v0.90.0-beta.0
  isolated-cluster    Prepopulating images/bundle for internet-restricted environments   global      v0.29.0
[...]
  telemetry           configure cluster-wide settings for vmware tanzu telemetry         kubernetes  v0.29.0

PS C:\Users\anujc\Downloads\tanzu-cli-windows-amd64\v0.90.0-rc.0> .\tanzu.exe plugin install isolated-cluster
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
```

**Output of `tanzu version`**

This happens since the `v0.90.0` release and continues with today's `main`: 225dbbda8

**Environment where the bug was observed (cloud, OS, etc)**

Windows

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

On Windows, trailing `.` are ignored in file names. But we used a file `metadata.digest.` with a trailing `.` when not using an airgapped image which is the most common case actually.

Since the trailing `.` gets ignored on Windows, the CLI never finds the `metadata.digest.` file and always thinks the cache is invalid.

This commit replaces the use of `metadata.digest.` with `metadata.digest.none`.

### Which issue(s) this PR fixes

Fixes #392

### Describe testing done for PR
Cache testing on Windows:
```

PS C:\Users\marck> .\tanzu.exe version
version: v1.0.0-dev
buildDate: 2023-07-08
sha: e4e58eb90

# A first download since the DB has changed on the remote since I last used it
PS C:\Users\marck> .\tanzu.exe plugin search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  NAME                  DESCRIPTION                                                                       TARGET           LATEST
  builder               Build Tanzu components                                                            global           v0.90.1
  isolated-cluster      Prepopulating images/bundle for internet-restricted environments                  global           v0.29.0
[...]
  workspace             A group of Kubernetes namespaces                                                  mission-control  v0.1.1

# The cache works now!
PS C:\Users\marck> .\tanzu-cli-windows_amd64.exe plugin search
  NAME                  DESCRIPTION                                                                       TARGET           LATEST
  builder               Build Tanzu components                                                            global           v0.90.1
  isolated-cluster      Prepopulating images/bundle for internet-restricted environments                  global           v0.29.0
[...]
  workspace             A group of Kubernetes namespaces                                                  mission-control  v0.1.1

# Notice the new `metadata.digest.none` file.
# Also, the old `metadata.digest` is not removed because the CLI looks for `metadata.digest.*`
# I feel this is ok:
#  1. it will only happen for someone that has used v0.90.0 or v0.90.1
#  2. this old file will be ignored by the new CLI
#  3. this old file is only on Windows where the trailing `.` is ignored
PS C:\Users\marck> ls .\.cache\tanzu\plugin_inventory\default\


    Directory: C:\Users\marck\.cache\tanzu\plugin_inventory\default


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023-07-07  11:41 PM              0 digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7
                                                  e8a9ff7
-a----        2023-07-07  11:41 PM              0 metadata.digest
-a----        2023-07-07  11:43 PM              0 metadata.digest.none
-a----        2023-07-07  11:43 PM          98304 plugin_inventory.db

# The cache continues to work
PS C:\Users\marck> .\tanzu.exe plugin group search
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0

# Point to a different central repo: the cache is invalid as expected
PS C:\Users\marck> .\tanzu.exe plugin source update default -u projects.registry.vmware.com/tanzu_cli_stage/plugins/plugin-inventory:latest
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli_stage/plugins/plugin-inventory:latest", this will take a few seconds.
[ok] updated discovery source default

# Cache still works
PS C:\Users\marck> .\tanzu.exe plugin group search
  GROUP                                           DESCRIPTION                     LATEST
  vmware-tap/default                              Plugins for TAP                 v1.6.0-rc.2
  vmware-tkg/default                              Plugins for TKG                 v2.2.0
  vmware-tkg/tkg-ob-464796462228756226-g885cc5ad  Plugin group for Halifax.0 RC1  v2.3.0

# main digest has changed and `metadata.digest.none` remains
PS C:\Users\marck> ls .\.cache\tanzu\plugin_inventory\default\


    Directory: C:\Users\marck\.cache\tanzu\plugin_inventory\default


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023-07-08   9:20 AM              0 digest.b09f2a15c2c7dc4168e852d11453fee7012d87ce54bc4180b770fd8fc
                                                  4ec1280
-a----        2023-07-07  11:41 PM              0 metadata.digest
-a----        2023-07-07  11:43 PM              0 metadata.digest.none
-a----        2023-07-08   9:20 AM          69632 plugin_inventory.db

# Switch back to the main central repo
PS C:\Users\marck> .\tanzu.exe plugin source init
[ok] successfully initialized discovery source

# Cache is invalid, as expected
PS C:\Users\marck> .\tanzu.exe plugin group search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0

# Main digest file changed as expected 
PS C:\Users\marck> ls .\.cache\tanzu\plugin_inventory\default\


    Directory: C:\Users\marck\.cache\tanzu\plugin_inventory\default


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023-07-08   9:21 AM              0 digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7
                                                  e8a9ff7
-a----        2023-07-07  11:41 PM              0 metadata.digest
-a----        2023-07-07  11:43 PM              0 metadata.digest.none
-a----        2023-07-08   9:21 AM          98304 plugin_inventory.db
```

Regression testing on Mac:
```
$ rm ~/.cache/tanzu/plugin_inventory
$ rm ~/.config/tanzu/config*
$ tz config eula accept
[ok] Marking agreement as accepted.
$ make start-test-central-repo
[...]

# Prepare the skip list
$ tz config set env.TANZU_CLI_PLUGIN_DISCOVERY_IMAGE_SIGNATURE_VERIFICATION_SKIP_LIST localhost:9876/tanzu-cli/plugins/airgapped:small,localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small

# Point to a central repo and notice the cache is refreshed as expected
$ tz plugin source update default -u localhost:9876/tanzu-cli/plugins/airgapped:small
[i] Reading plugin inventory for "localhost:9876/tanzu-cli/plugins/airgapped:small", this will take a few seconds.
[!] Skipping the plugins discovery image signature verification for "localhost:9876/tanzu-cli/plugins/airgapped:small"

[ok] updated discovery source default

# Cache is re-used
$ tz plugin group search
  GROUP                DESCRIPTION                          LATEST
  vmware-tkg/default   Desc for vmware-tkg/default:v9.9.9   v9.9.9
  vmware-tmc/tmc-user  Desc for vmware-tmc/tmc-user:v9.9.9  v9.9.9

# Download plugins for air-gapped
$ tz plugin download-bundle --image localhost:9876/tanzu-cli/plugins/airgapped:small --group vmware-tkg/default --to-tar plugin_bundle1.tar
[!] Skipping the plugins discovery image signature verification for "localhost:9876/tanzu-cli/plugins/airgapped:small"

[i] will be downloading the one plugin from group: vmware-tkg/default:v9.9.9
[i] downloading image "localhost:9876/tanzu-cli/plugins/airgapped:small"
[i] copy | exporting 2 images...
[...]
[i] copy | writing layers...
[i] copy | done: file 'manifest.json' (6.208µs)
[i] copy | done: file 'sha256-bed3e352bcda48d967dad08b19dffac9b38bb4a2c5d0f9df10d7f0a69e226a1e.tar.gz' (58.292µs)
[i] saving plugin bundle at: plugin_bundle1.tar

# Upload to the air-gapped repo
$ tz plugin upload-bundle --tar plugin_bundle1.tar  --to-repo localhost:9876/test/airgapped/v1/tanzu-cli/plugins
[i] extracting "plugin_bundle1.tar" for processing...
[i] ---------------------------
[i] uploading image "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped"
[i] copy | importing 2 images...

4.93 KiB / 269 B [-------------------------------------------------------------------------------------------------------------------] 1876.58% 48.20 KiB p/s
[...]
[i] publishing plugin inventory metadata image...
[i] plugin inventory metadata image "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped-metadata:small" is not present. Skipping merging of the plugin inventory metadata
[i] uploading image "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped-metadata:small"
[i] ---------------------------
[i] successfully published all plugin images to "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small"

# Point to the air-gapped repo: the cached is invalid as expected
$ tz plugin source update default -u localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small
[i] Reading plugin inventory for "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small", this will take a few seconds.
[!] Skipping the plugins discovery image signature verification for "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small"

[ok] updated discovery source default

# the metadata.digest file looks right for an air-gapped repo
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.16cac57a12bd21e7f8ee1c8aa16300b46bffa171319b11d79d4998eb29f4567d
    ├── metadata.digest.8f15ce9926557fcf0cd3788daf0b09a73daaf25a300b7266a9094ee0beb33571
    └── plugin_inventory.db

1 directory, 3 files

# Cache is valid, as expected
$ tz plugin group search
  GROUP               DESCRIPTION                         LATEST
  vmware-tkg/default  Desc for vmware-tkg/default:v9.9.9  v9.9.9

# Switch back to the original repo.
# This is the scenario that we have to be careful about:
# the DB digest is the same as for the air-gapped repo but there
# is not metadata file anymore.  Notice the cache is properly invalidated.
$ tz plugin source update default -u localhost:9876/tanzu-cli/plugins/airgapped:small
[i] Reading plugin inventory for "localhost:9876/tanzu-cli/plugins/airgapped:small", this will take a few seconds.
[!] Skipping the plugins discovery image signature verification for "localhost:9876/tanzu-cli/plugins/airgapped:small"

[ok] updated discovery source default

# Notice the new `.none` suffix for the metatadafile
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.16cac57a12bd21e7f8ee1c8aa16300b46bffa171319b11d79d4998eb29f4567d
    ├── metadata.digest.none
    └── plugin_inventory.db

1 directory, 3 files

# Cache remains valid as expected
$ tz plugin group search
  GROUP                DESCRIPTION                          LATEST
  vmware-tkg/default   Desc for vmware-tkg/default:v9.9.9   v9.9.9
  vmware-tmc/tmc-user  Desc for vmware-tmc/tmc-user:v9.9.9  v9.9.9

# Switch to the main central repo
$ tz plugin source init
[ok] successfully initialized discovery source

# Cache is invalid, as expected
$ tz plugin group search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0

# Main digest is different, but metadatafile remains with the `.none` suffix
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7e8a9ff7
    ├── metadata.digest.none
    └── plugin_inventory.db

1 directory, 3 files

# Go back to the airgapped repo: the cache is invalid, as expected
$ tz plugin source update default -u localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small
[i] Reading plugin inventory for "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small", this will take a few seconds.
[!] Skipping the plugins discovery image signature verification for "localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small"

[ok] updated discovery source default

# Back to two digest files
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.16cac57a12bd21e7f8ee1c8aa16300b46bffa171319b11d79d4998eb29f4567d
    ├── metadata.digest.8f15ce9926557fcf0cd3788daf0b09a73daaf25a300b7266a9094ee0beb33571
    └── plugin_inventory.db

1 directory, 3 files

# Point to the same air-gapped repo: the cache is valid, as expected
$ tz plugin source update default -u localhost:9876/test/airgapped/v1/tanzu-cli/plugins/airgapped:small
[ok] updated discovery source default

# No change, as expected
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.16cac57a12bd21e7f8ee1c8aa16300b46bffa171319b11d79d4998eb29f4567d
    ├── metadata.digest.8f15ce9926557fcf0cd3788daf0b09a73daaf25a300b7266a9094ee0beb33571
    └── plugin_inventory.db

1 directory, 3 files

# Go back to the repo on which the air-gapped one is based: the cache is invalid, as expected.
# Notice that the main digest number is the same as for the air-gapped repo above, but that
# the change in metadata file causes the cache refresh as expected.
$ tz plugin source update default -u localhost:9876/tanzu-cli/plugins/airgapped:small
[i] Reading plugin inventory for "localhost:9876/tanzu-cli/plugins/airgapped:small", this will take a few seconds.
[!] Skipping the plugins discovery image signature verification for "localhost:9876/tanzu-cli/plugins/airgapped:small"

[ok] updated discovery source default
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.16cac57a12bd21e7f8ee1c8aa16300b46bffa171319b11d79d4998eb29f4567d
    ├── metadata.digest.none
    └── plugin_inventory.db

1 directory, 3 files
```

Backwards-compatibility test:
```
$ rm ~/.cache/tanzu/plugin_inventory
$ rm ~/.config/tanzu/config*
$ tz config eula accept
[ok] Marking agreement as accepted.

# Run v0.90.1 to generate a `metadata.digest.` file
$ /opt/homebrew/bin/tanzu version
version: v0.90.1
buildDate: 2023-06-29
sha: 8945351c
$ /opt/homebrew/bin/tanzu plugin group search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7e8a9ff7
    ├── metadata.digest.
    └── plugin_inventory.db

1 directory, 3 files

# Now run this PR and notice that the cache is seen as invalid
# because of the change of name from `metadata.digest.` to `metadata.digest.none`
# This is a small side-effect of this change that is not a big problem.
$ tz version
version: v1.0.0-dev
buildDate: 2023-07-08
sha: e4e58eb90
$ tz plugin group search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7e8a9ff7
    ├── metadata.digest.none
    └── plugin_inventory.db

1 directory, 3 files

# Switch back to an old CLI and the cache is invalidated again.
# I still feel this is acceptable.
$ /opt/homebrew/bin/tanzu plugin group search
[i] Reading plugin inventory for "projects.registry.vmware.com/tanzu_cli/plugins/plugin-inventory:latest", this will take a few seconds.
  GROUP               DESCRIPTION      LATEST
  vmware-tkg/default  Plugins for TKG  v2.2.0
$ tree ~/.cache/tanzu/plugin_inventory
/Users/kmarc/.cache/tanzu/plugin_inventory
└── default
    ├── digest.35400d6a7cd6c90f49eb22aeeb56ec4629d8baef0dbd22560497d73a7e8a9ff7
    ├── metadata.digest.
    └── plugin_inventory.db

1 directory, 3 files
```

### Release note

```release-note
The plugin inventory caching is fixed for Windows systems.
```

#### Alternative approach considered

I started with a solution that would not use the empty `metadata.digest.` file at all, but would properly recognize when the cache needed to be invalidated.

But after working on it a bit, I felt it was introducing more risk than necessary, late in the cycle.
Also, with the use of `metadata.digest.none`, I felt that having such an "empty" metadata file was actually nice and informative.

I therefore went with the proposed solution of simply using `metadata.digest.none` instead of `metadata.digest.`, which re-uses all the existing code and reduces risk a lot.

#### Backwards-compatibility

_Mac and Linux:_
The first time the CLI using this PR is used, the cache will be invalid because of the change of name from `metadata.digest.` to `metadata.digest.none`. 
If a user goes back to an older CLI, the cache will also be invalid.

This extra DB download will happen whenever switching between a CLI using this PR and and older one.

This is an impact that I feel is acceptable and not worth complicating the code to try to avoid.  

Note that any previous `metadata.digest.` file will be removed by the new CLI and replaced by `metadata.digest.none`

_Windows:_
The cache was not working at all, so there is no extra impact due to extra DB downloads.

**Note**: the old `metadata.digest` file will not be removed because the CLI looks for `metadata.digest.*` with the trailing `.`. I feel this is ok:
1. it will only happen for someone that has used `v0.90.0` or `v0.90.1`
2. this old file will be ignored by the new CLI
3. this old file is only on Windows where the trailing `.` is ignored

We could address the backwards-compatibility situation by moving any `metadata.digest.` file to `metadata.digest.none`.  What I don't like about this is that we'd keep making that check every time we check the cache, even though this need only be done once.

Opinions?

### CODE REVIEW

**Review by vuil — APPROVED** [review]
lgtm, thanks for the detailed explanation.
On the backward compatibility questions:

From what I can see, the impacts are
- an incorrect cache invalidation when switching between versions of cli before and after the fix
- a stray file on windows.
Both are totally acceptable imo.

Thanks for fixing the comments along the way.
While you are at it, can you also update another preexisting error in L:242-245 of checkImageCache's function comment?

**Comment by marckhouzam** [comment]
Thanks @vuil

> nit: While you are at it, can you also update another preexisting error in L:242-245 of checkImageCache's function comment?

Good idea. Done.

**Review by vuil — APPROVED** [review]
lgtm, thanks!

**Review by anujc25 — APPROVED** [review]
LGTM. Thanks for the detailed explanation.

**Pull request merged**
