### PR TITLE
Remove deprecated components

### PR DESCRIPTION
**Pull request by mpanchajanya**
### What this PR does / why we need it

Removed below components

Commands:

- tz builder cli compile (newCompileCmd())
- tz builder publish (NewPublishCmd())
- tz config server (and its sub commands) (variable serversCmd)

Cleanup:

- pkg/command/config.go has code to set "unstable-versions" and "cli.edition" which is not supported and private functions are deprecated (setUnstableVersions() and setEdition())
- pkg/config/bom.go and pkg/config/edition.go can all be removed

Remove use of deprecated items:

- use of PluginDiscovery.GCP

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

- Verified adding discovery source
- Verified the removed commands of servers
```
mpanchajanya@mpanchajanF09MK ~/v/r/tanzu-cli (remove_deprecated_components)> tz config
Configuration for the CLI

Usage:
  tanzu config [command]

Available Commands:
  cert        Manage certificate configuration of hosts
  eula        Manage EULA acceptance
  get         Get the current configuration
  init        Initialize config with defaults
  set         Set config values at the given PATH
  unset       Unset config values at the given PATH

Flags:
  -h, --help   help for config

Use "tanzu config [command] --help" for more information about a command.

```

### Release note

```release-note
Removed commands tanzu builder cli compile,  tanzu builder publish, tanzu config server (and its sub commands) 
```

### CODE REVIEW

**Review by anujc25 — APPROVED** [review]
Changes looks good.

We need to add details about the removed commands in the release note. Please add more details before merging.

**Review by marckhouzam — COMMENTED** [review]
Thanks for this cleanup!  It's just missing some doc updates mentioned below and possibly a bit more cleanup.

A couple of minor points:
1. the README of the builder plugin still mentions `tanzu builder cli compile`
2. same for cli-architecture.md
3. in quickstart.md in the section about `tanzu config server`, can you replace the word 'deprecated' by 'removed'
4. can you remove the mention of `tanzu config server` in cli-architecture.md
5. I think we can also remove the entire directory `cmd/plugin/builder/command/publish` but I'd like @anujc25 to confirm
6. should we remove `ConfigServerDelete` and `ConfigServerList` and `ConfigServerDeleted` from `test/e2e/framework/framework_constants.go`?

**Comment by mpanchajanya** [comment]
> Changes looks good.
> 
> We need to add details about the removed commands in the release note. Please add more details before merging.

Thanks for the review. Updated the release notes

**Comment by mpanchajanya** [comment]
> 6\. ConfigServerDeleted

Thanks @marckhouzam  for the review. I have the updated the markdown files and removed server methods from e2e. Will wait for @anujc25  on 5)I think we can also remove the entire directory cmd/plugin/builder/command/publish but I'd like @anujc25 to confirm

**Comment by anujc25** [comment]
> I think we can also remove the entire directory cmd/plugin/builder/command/publish but I'd like @anujc25 to confirm

Yes. We can remove the entire directory.

**Review by marckhouzam — APPROVED** [review]
LGTM
Thank you

**Pull request merged**
