### PR TITLE
Update doc regarding `go.mod` update  to point to `tanzu-plugin-runtime`

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it
- Update doc regarding `go.mod` update  to point to `tanzu-plugin-runtime`

### Which issue(s) this PR fixes

Fixes #

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by mpanchajanya — APPROVED** [review]
LGTM

**Review by vuil — APPROVED** [review]
lgtm, thanks.

**Comment by mpanchajanya** [comment]
@anujc25  Could you also update here as well  https://github.com/vmware-tanzu/tanzu-cli/blob/main/docs/plugindev/migrate.md#updating-the-plugin-code-and-dependencies

**Review by vuil — APPROVED** [review]
lgtm

**Review by marckhouzam — APPROVED** [review]
LGTM

**Review by vuil — APPROVED** [review]
lgtm as short term workaround.

**Review by vuil — APPROVED** [review]
lgtm

**Pull request merged**
