### PR TITLE
"plugin search" should only discovers from central repos

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

After discussion, we have decided that "plugin search" should:
- not show the status or the context
- only show plugins found in the central repo (not ones discovered from a context

So the columns should be :
```
NAME
DESCRIPTION
TARGET
LATEST VERSION. (I have changed this to just LATEST for the sake of space)
```
So this commit makes the "plugin search" command no longer show context-scope plugins which are not part of the central repositories.
Also the "plugin search" command no longer shows status or context information, which is the responsibility of the "plugin list" command.

### Describe testing done for PR

```
# Reset first
$ rm ~/.config/tanzu/config*
$ tz plugin clean
[ok] successfully cleaned up all plugins
$
$ tz config set env.TANZU_CLI_PRE_RELEASE_REPO_IMAGE localhost:9876/tanzu-cli/plugins/central:small
$ make start-test-central-repo
[...]

# Notice the new output
$ tz plugin search
  NAME                DESCRIPTION                  TARGET           LATEST
  isolated-cluster    Desc for isolated-cluster    global           v9.9.9
  pinniped-auth       Desc for pinniped-auth       global           v9.9.9
[...]
  secret              Desc for secret              mission-control  v9.9.9
  tanzupackage        Desc for tanzupackage        mission-control  v9.9.9
  workspace           Desc for workspace           mission-control  v9.9.9

# Create a context which installs plugins with version v0.0.1
$ tz context create --name k3d --kubecontext k3d --kubeconfig /Users/kmarc/.kube/config.k3d
[ok] successfully created a kubernetes context using the kubeconfig /Users/kmarc/.kube/config.k3d
[i] Checking for required plugins...
[i] Installing plugin 'cluster:v0.0.1' with target 'kubernetes'
[i] Installing plugin 'feature:v0.0.1' with target 'kubernetes'
[i] Installing plugin 'kubernetes-release:v0.0.1' with target 'kubernetes'
[i] Installing plugin 'package:v0.0.1' with target 'kubernetes'
[i] Successfully installed all required plugins

# Notice that the LATEST version column shows the content of the central repo
# not what is installed
tz plugin search
  NAME                DESCRIPTION                  TARGET           LATEST
  isolated-cluster    Desc for isolated-cluster    global           v9.9.9
  pinniped-auth       Desc for pinniped-auth       global           v9.9.9
  cluster             Desc for cluster             kubernetes       v9.9.9
  feature             Desc for feature             kubernetes       v9.9.9
  kubernetes-release  Desc for kubernetes-release  kubernetes       v9.9.9
  management-cluster  Desc for management-cluster  kubernetes       v9.9.9
  package             Desc for package             kubernetes       v9.9.9
  secret              Desc for secret              kubernetes       v9.9.9
  telemetry           Desc for telemetry           kubernetes       v9.9.9
  account             Desc for account             mission-control  v9.9.9
  apply               Desc for apply               mission-control  v9.9.9
[...]
  workspace           Desc for workspace           mission-control  v9.9.9

# Add a test repo that contains newer v11.11.11 versions
$ tz config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY localhost:9876/tanzu-cli/plugins/sandbox1:small

# Notice the output show the latest available version
$ tz plugin search
  NAME                DESCRIPTION                  TARGET           LATEST
  isolated-cluster    Desc for isolated-cluster    global           v9.9.9
  pinniped-auth       Desc for pinniped-auth       global           v9.9.9
  cluster             Desc for cluster             kubernetes       v11.11.11
  feature             Desc for feature             kubernetes       v11.11.11
  kubernetes-release  Desc for kubernetes-release  kubernetes       v11.11.11
  management-cluster  Desc for management-cluster  kubernetes       v11.11.11
  package             Desc for package             kubernetes       v11.11.11
  secret              Desc for secret              kubernetes       v11.11.11
  telemetry           Desc for telemetry           kubernetes       v11.11.11
  account             Desc for account             mission-control  v11.11.11
  apply               Desc for apply               mission-control  v11.11.11
[...]
  tanzupackage        Desc for tanzupackage        mission-control  v11.11.11
  workspace           Desc for workspace           mission-control  v11.11.11

# Add two test repos that contains newer v11.11.11 and v22.22.22 versions
$ tz config set env.TANZU_CLI_ADDITIONAL_PLUGIN_DISCOVERY_IMAGES_TEST_ONLY localhost:9876/tanzu-cli/plugins/sandbox1:small,localhost:9876/tanzu-cli/plugins/sandbox2:small

# Notice the v22.22.22 now showing since it is the latest
$ tz plugin search
  NAME                DESCRIPTION                  TARGET           LATEST
  isolated-cluster    Desc for isolated-cluster    global           v9.9.9
  pinniped-auth       Desc for pinniped-auth       global           v9.9.9
  cluster             Desc for cluster             kubernetes       v22.22.22
  feature             Desc for feature             kubernetes       v22.22.22
  kubernetes-release  Desc for kubernetes-release  kubernetes       v22.22.22
  management-cluster  Desc for management-cluster  kubernetes       v22.22.22
  package             Desc for package             kubernetes       v22.22.22
  secret              Desc for secret              kubernetes       v22.22.22
  telemetry           Desc for telemetry           kubernetes       v22.22.22
  account             Desc for account             mission-control  v22.22.22
[...]
  tanzupackage        Desc for tanzupackage        mission-control  v22.22.22
  workspace           Desc for workspace           mission-control  v22.22.22

$ tz plugin search -o yaml
- description: Desc for isolated-cluster
  latest: v9.9.9
  name: isolated-cluster
  target: global
- description: Desc for pinniped-auth
  latest: v9.9.9
  name: pinniped-auth
  target: global
- description: Desc for cluster
  latest: v9.9.9
  name: cluster
  target: kubernetes
- description: Desc for feature
  latest: v9.9.9
  name: feature
  target: kubernetes
- description: Desc for kubernetes-release
  latest: v9.9.9
  name: kubernetes-release
  target: kubernetes
- description: Desc for management-cluster
  latest: v9.9.9
  name: management-cluster
  target: kubernetes
- description: Desc for package
  latest: v9.9.9
  name: package
  target: kubernetes
- description: Desc for secret
  latest: v9.9.9
  name: secret
  target: kubernetes
- description: Desc for telemetry
  latest: v9.9.9
  name: telemetry
  target: kubernetes
- description: Desc for account
  latest: v9.9.9
  name: account
  target: mission-control
[...]
- description: Desc for tanzupackage
  latest: v9.9.9
  name: tanzupackage
  target: mission-control
- description: Desc for workspace
  latest: v9.9.9
  name: workspace
  target: mission-control

# Use plugin search with a local repo
# Notice that only what is discovered is shown, not what is installed (compared to plugin list below)
$ tz plugin search --local ~/.config/tanzu-plugins/
  NAME                DESCRIPTION                                                        TARGET      LATEST
  builder             Build Tanzu components                                                         v0.29.0-dev
  codegen             Tanzu code generation tool                                                     v0.29.0-dev
  isolated-cluster    Prepopulating images/bundle for internet-restricted environments               v0.29.0-dev
  login               Login to the platform                                                          v0.29.0-dev
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)              v0.29.0-dev
  test                Test the CLI                                                                   v0.29.0-dev
  cluster             Kubernetes cluster operations                                      kubernetes  v0.29.0-dev
  feature             Operate on features and featuregates                               kubernetes  v0.29.0-dev
  kubernetes-release  Kubernetes release operations                                      kubernetes  v0.29.0-dev
  management-cluster  Kubernetes management cluster operations                           kubernetes  v0.29.0-dev
  package             Tanzu package management                                           kubernetes  v0.29.0-dev
  secret              Tanzu secret management                                            kubernetes  v0.29.0-dev
  telemetry           configure cluster-wide settings for vmware tanzu telemetry         kubernetes  v0.29.0-dev
$ tz plugin list
Standalone Plugins
  NAME  DESCRIPTION  TARGET  VERSION  STATUS

Plugins from Context:  k3d
  NAME                DESCRIPTION                           TARGET      VERSION  STATUS
  cluster             Kubernetes cluster operations         kubernetes  v0.0.1   installed
  feature             Operate on features and featuregates  kubernetes  v0.0.1   installed
  kubernetes-release  Kubernetes release operations         kubernetes  v0.0.1   installed
  package             Operate on packages                   kubernetes  v0.0.1   installed

$ tz plugin search --local ~/.config/tanzu-plugins/ -o json
[
  {
    "description": "Build Tanzu components",
    "latest": "v0.29.0-dev",
    "name": "builder",
    "target": ""
  },
  {
    "description": "Tanzu code generation tool",
    "latest": "v0.29.0-dev",
    "name": "codegen",
    "target": ""
  },
  {
    "description": "Prepopulating images/bundle for internet-restricted environments",
    "latest": "v0.29.0-dev",
    "name": "isolated-cluster",
    "target": ""
  },
  {
    "description": "Login to the platform",
    "latest": "v0.29.0-dev",
    "name": "login",
    "target": ""
  },
  {
    "description": "Pinniped authentication operations (usually not directly invoked)",
    "latest": "v0.29.0-dev",
    "name": "pinniped-auth",
    "target": ""
  },
  {
    "description": "Test the CLI",
    "latest": "v0.29.0-dev",
    "name": "test",
    "target": ""
  },
  {
    "description": "Kubernetes cluster operations",
    "latest": "v0.29.0-dev",
    "name": "cluster",
    "target": "kubernetes"
  },
  {
    "description": "Operate on features and featuregates",
    "latest": "v0.29.0-dev",
    "name": "feature",
    "target": "kubernetes"
  },
  {
    "description": "Kubernetes release operations",
    "latest": "v0.29.0-dev",
    "name": "kubernetes-release",
    "target": "kubernetes"
  },
  {
    "description": "Kubernetes management cluster operations",
    "latest": "v0.29.0-dev",
    "name": "management-cluster",
    "target": "kubernetes"
  },
  {
    "description": "Tanzu package management",
    "latest": "v0.29.0-dev",
    "name": "package",
    "target": "kubernetes"
  },
  {
    "description": "Tanzu secret management",
    "latest": "v0.29.0-dev",
    "name": "secret",
    "target": "kubernetes"
  },
  {
    "description": "configure cluster-wide settings for vmware tanzu telemetry",
    "latest": "v0.29.0-dev",
    "name": "telemetry",
    "target": "kubernetes"
  }
]
```

### Release note

```release-note
The "tanzu plugin search" command no longer shows installation status or context information; the "tanzu plugin list" command should be used to obtain such information"
```

### CODE REVIEW

**Review by mpanchajanya — COMMENTED** [review]
LGTM!
nit: e2e tests failed

**Comment by marckhouzam** [comment]
> Can you also add `-o json` and `-o yaml` output sample as part of the PR description for the `tanzu plugin search` command?

Good point, I forgot. However, I need to first get an agreement on what the title of the version column should be as it will affect this output.

So we want to use:
-  "VERSION" like the other commands
-  "LATEST VERSION" which is more informative, but I found pretty long in the output
- "LATEST" which aims to get the best of both

**Comment by anujc25** [comment]
> So what do we want to use?
> 
> * "VERSION" like the other commands
> * "LATEST VERSION" which is more informative, but I found pretty long in the output
> * "LATEST" which aims to get the best of both

I like the `LATEST` option as well.

**Review by anujc25 — APPROVED** [review]
LGTM.

**Pull request merged**
