### PR TITLE
Fix the file locking issue on Windows

### PR DESCRIPTION
**Pull request by anujc25**
### What this PR does / why we need it

- For more details see: https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/204

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
- Build the Tanzu CLI for Windows, Mac, Linux with the fix
- Verify that CLI can install and run the `package` and `space` plugin (built with older Tanzu Plugin Runtime)

- Build the `space` plugin using v1.4.2 version of Tanzu Plugin Runtime
- Verify that CLI can install the `space` plugin (built with newer v1.4.2 Tanzu Plugin Runtime)

**Windows Tests:**
Screenshot 2024-08-08 at 2 54 54 PM

### Release note

```release-note
Fix the file locking issue on Windows
```

### CODE REVIEW

**Comment by vuil** [comment]
For completeness we should test interacting with a plugin built with 1.4.2 or TPR as well.

**Review by vuil — APPROVED** [review]
lgtm, but a nit request on the testing side just to be sure.

**Review by marckhouzam — APPROVED** [review]
Not essential but while bumping to use TPR 1.4.2, do you want to update the 2 other go.mod files in the repository?

LGTM either way

**Comment by anujc25** [comment]
> For completeness we should test interacting with a plugin built with 1.4.2 or TPR as well.

@vuil I built the `space` plugin with v1.4.2 of Tanzu Plugin Runtime and verified it on `Mac` and `Windows` both manually.

**Comment by anujc25** [comment]
> lgtm, but a nit request on the testing side just to be sure.

@vuil I have tested this on Mac, Linux and Windows all three and added details for windows in PR description.

**Comment by vuil** [comment]
Thanks for furnishing the test details. LGTM.

**Review by marckhouzam — APPROVED** [review]
LGTM

**Pull request merged**
