### PR TITLE
Document details of support for ARM64

### LINKED ISSUE #774: Documentation does not mention you need Rosetta on ARM Mac
**Bug description**
Documentation does not mention you need Rosetta on ARM Mac

**Expected behavior**
Documentation should mention for ARM Macs (M1/M2/M3) you need to execute:
```
softwareupdate --install-rosetta --agree-to-license
``` 

**Steps to reproduce the bug / Relevant debug output**
If you did not install Rosetta, installing plugins will fail with error `bad CPU type in executable`:
```
$ tanzu plugin list
[i] The tanzu cli essential plugins have not been installed and are being installed now. The install may take a few seconds.
[i] Installing plugins from plugin group 'vmware-tanzucli/essentials:v1.0.0'
[x] Failed to install plugin 'telemetry:v1.1.0' with target 'global'
[!] unable to install plugin 'telemetry': could not describe plugin "telemetry": fork/exec /Users/jeroenv/Library/Application Support/tanzu-cli/telemetry/v1.1.0_a93519154dc71368d738aec09f9bc964a0c3bcd02a856106ccaddaaf31426636_global: bad CPU type in executable
```
It took me quite a while to figure out what the problem was.

**Output of `tanzu version`**
```
$ tanzu version
version: v1.3.0
buildDate: 2024-05-09
sha: d59f47c8
arch: arm64
```
**Environment where the bug was observed (cloud, OS, etc)**
```
$  uname -a
Darwin Jeroens-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64
$ sysctl -a | grep brand
machdep.cpu.brand_string: Apple M1
```

### PR DESCRIPTION
**Pull request by marckhouzam**
### What this PR does / why we need it

As per a user's request, this PR adds information about how the CLI supports ARM64.

### Which issue(s) this PR fixes

Fixes #774 

### Describe testing done for PR

CI

### Release note

```release-note
Document details about ARM64 support.
```

### CODE REVIEW

**Comment by marckhouzam** [comment]
@jeroenvermeulen  if you can confirm if this documentation change would have been sufficient for you?

**Comment by jeroenvermeulen** [comment]
It points you in the right direction for sure.
Here in the Netherlands 95% of the Kubernetes experts are using macOS, so an explicit mention of the Rosetta install command would be even better.
```
softwareupdate --install-rosetta --agree-to-license
```

**Comment by marckhouzam** [comment]
> It points you in the right direction for sure. Here in the Netherlands 95% of the Kubernetes experts are using macOS, so an explicit mention of the Rosetta install command would be even better.
> 
> ```
> softwareupdate --install-rosetta --agree-to-license
> ```

I hesitated in doing that because I didn't feel giving an exact command was future-proof.  Who knows what Apple will change in any future OS release.  Was this command sufficiently easy to find on Google?  What I can do to make it easier is mention `Rosetta 2` as the name of the emulator for Mac.

What do you think?

**Review by prkalle — APPROVED** [review]
LGTM. Thanks.

**Comment by jeroenvermeulen** [comment]
@marckhouzam Thanks for fixing this so fast.

**Pull request merged**
